const fakeData = [
    {
        "category": 'burger',
        "id": 'BGX01',
        "name": 'Bigti Burger',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786131/testo-burger-project/all-food-items/burgers/bigti-burger_uhacul.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 12.95,
        "star": 5,
        "starCount": 46
    },
    {
        "category": 'burger',
        "id": 'BGX02',
        "name": 'Black Sheep',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786130/testo-burger-project/all-food-items/burgers/black-sheep_hyk4vg.jpg',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 9.75,
        "star": 4,
        "starCount": 7
    },
    {
        "category": 'burger',
        "id": 'BGX03',
        "name": 'Classic Burger',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786133/testo-burger-project/all-food-items/burgers/classic-burger_qr27pp.jpg',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 7.95,
        "star": 5,
        "starCount": 12
    },
    {
        "category": 'burger',
        "id": 'BGX04',
        "name": 'Crispy Chicken',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786134/testo-burger-project/all-food-items/burgers/crispy-chicken_k46dxd.jpg',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 8.50,
        "star": 4,
        "starCount": 10
    },
    {
        "category": 'burger',
        "id": 'BGX05',
        "name": 'Double Burger',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786133/testo-burger-project/all-food-items/burgers/double-burger_ipj10l.jpg',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 10.35,
        "star": 5,
        "starCount": 19
    },
    {
        "category": 'burger',
        "id": 'BGX06',
        "name": 'Holm Burger',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786134/testo-burger-project/all-food-items/burgers/holm-burger_zlgtmd.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 11.35,
        "star": 5,
        "starCount": 17
    },
    {
        "category": 'burger',
        "id": 'BGX07',
        "name": 'Komil Burger',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786133/testo-burger-project/all-food-items/burgers/komil-burger_kzqaqv.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 11.40,
        "star": 5,
        "starCount": 22
    },
    {
        "category": 'burger',
        "id": 'BGX08',
        "name": 'Smokey House',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786134/testo-burger-project/all-food-items/burgers/smokey-house_rszvfb.jpg',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 9.50,
        "star": 3,
        "starCount": 68
    },
    {
        "category": 'burger',
        "id": 'BGX09',
        "name": 'Sough Burger',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786134/testo-burger-project/all-food-items/burgers/sough-burger_srlxu4.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 9.95,
        "star": 5,
        "starCount": 37
    },
    {
        "category": 'burger',
        "id": 'BGX10',
        "name": 'Spanish Burger',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786135/testo-burger-project/all-food-items/burgers/spanish-burger_zw9uqs.jpg',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 8.95,
        "star": 4,
        "starCount": 19
    },
    {
        "category": 'burger',
        "id": 'BGX11',
        "name": 'Turkey Burger',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786134/testo-burger-project/all-food-items/burgers/turkey-burger_far3sh.jpg',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 8.95,
        "star": 4,
        "starCount": 8
    },
    {
        "category": 'burger',
        "id": 'BGX12',
        "name": 'Ultimate Bacon',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786134/testo-burger-project/all-food-items/burgers/ultimate-bacon_nn0zka.jpg',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 9.99,
        "star": 5,
        "starCount": 49
    },
    {
        "category": 'desserts',
        "id": 'DSX01',
        "name": 'Belgian Waffle',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786134/testo-burger-project/all-food-items/desserts/belgian-waffle_adyeue.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 7.98,
        "star": 5,
        "starCount": 51
    },
    {
        "category": 'desserts',
        "id": 'DSX02',
        "name": 'Cheese Cake',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786135/testo-burger-project/all-food-items/desserts/cheese-cake_kn3del.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 7.99,
        "star": 5,
        "starCount": 105
    },
    {
        "category": 'desserts',
        "id": 'DSX03',
        "name": 'Chocolate Cake',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786135/testo-burger-project/all-food-items/desserts/chocolate-cake_aqauyo.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 7.99,
        "star": 5,
        "starCount": 101
    },
    {
        "category": 'desserts',
        "id": 'DSX04',
        "name": 'Strawberry Cake',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786135/testo-burger-project/all-food-items/desserts/strawberry-cake_zxkqdo.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 8.15,
        "star": 5,
        "starCount": 99
    },
    {
        "category": 'pasta',
        "id": 'PSX01',
        "name": 'Fettuccine Alfredo',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786135/testo-burger-project/all-food-items/pasta/fettuccine-alfredo_oc8xcn.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 7.55,
        "star": 5,
        "starCount": 5
    },
    {
        "category": 'pasta',
        "id": 'PSX02',
        "name": 'Pancetta Spaghetti',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786135/testo-burger-project/all-food-items/pasta/pancetta-spaghetti_xvus4v.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 8.25,
        "star": 4,
        "starCount": 9
    },
    {
        "category": 'pasta',
        "id": 'PSX03',
        "name": 'Spaghetti Bolognese',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786136/testo-burger-project/all-food-items/pasta/spaghetti-bolognese_boc39w.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 9.75,
        "star": 5,
        "starCount": 12
    },
    {
        "category": 'pasta',
        "id": 'PSX04',
        "name": 'Tuna Pasta Bake',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786136/testo-burger-project/all-food-items/pasta/tuna-pasta-bake_oxk6zi.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 9.87,
        "star": 5,
        "starCount": 19
    },
    {
        "category": 'pizza',
        "id": 'PZX01',
        "name": 'Buffalo Chicken Pizza',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786136/testo-burger-project/all-food-items/pizza/buffalo-chicken-pizza_nblcwo.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 12.99,
        "star": 4,
        "starCount": 18
    },
    {
        "category": 'pizza',
        "id": 'PZX02',
        "name": 'Prosciuttio & Arugula Pizza',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786136/testo-burger-project/all-food-items/pizza/prosciuttio-_-arugula-pizza_k5cwd1.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 12.15,
        "star": 5,
        "starCount": 16
    },
    {
        "category": 'pizza',
        "id": 'PZX03',
        "name": 'Spicy BBQ Chicken Pizza',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786136/testo-burger-project/all-food-items/pizza/spicy-bbq-chicken-pizza_twvzaz.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 12.55,
        "star": 4,
        "starCount": 8
    },
    {
        "category": 'salads',
        "id": 'SLX01',
        "name": 'Chicken Salad',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786137/testo-burger-project/all-food-items/salads/chicken-salad_g4opzc.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 7.98,
        "star": 5,
        "starCount": 91
    },
    {
        "category": 'salads',
        "id": 'SLX02',
        "name": 'Greek Salad',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786136/testo-burger-project/all-food-items/salads/greek-salad_lee3hm.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 8.25,
        "star": 4,
        "starCount": 24
    },
    {
        "category": 'salads',
        "id": 'SLX03',
        "name": 'Spinach Salad',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786137/testo-burger-project/all-food-items/salads/spinach-salad_lrwrsi.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 6.95,
        "star": 4,
        "starCount": 16
    },
    {
        "category": 'salads',
        "id": 'SLX04',
        "name": 'Turkey Salad',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786137/testo-burger-project/all-food-items/salads/turkey-salad_zk6kme.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 7.95,
        "star": 5,
        "starCount": 9
    },
    {
        "category": 'sides',
        "id": 'SDX01',
        "name": 'Chicken Nuggets',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786137/testo-burger-project/all-food-items/sides/chicken-nuggets_tcyglp.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 18.90,
        "star": 5,
        "starCount": 11
    },
    {
        "category": 'sides',
        "id": 'SDX02',
        "name": 'French Fries',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786137/testo-burger-project/all-food-items/sides/french-fries_e8hc62.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 11.88,
        "star": 5,
        "starCount": 127
    },
    {
        "category": 'sides',
        "id": 'SDX03',
        "name": 'Mozzarella Sticks',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786138/testo-burger-project/all-food-items/sides/mozzarella-sticks_z1p9hi.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 8.50,
        "star": 5,
        "starCount": 103
    },
    {
        "category": 'sides',
        "id": 'SDX04',
        "name": 'Onion Rings',
        "image": 'https://res.cloudinary.com/dn9k2jkdd/image/upload/v1649786137/testo-burger-project/all-food-items/sides/onion-rings_r1ok6a.png',
        "briefInfo": 'Mushroom patty, vegan cheese, lettuce, tomatoes, avocado ligula',
        "description": 'Aliqum mullam blandit tempor sapien gravida donec ipsum, at porta justo. Velna vitae auctor congue magna nihil impedit ligula risus. Mauris donec ociis et magnis sapien sagittis sapien sem congue tempor gravida donec enim ipsum porta justo integer odio velna a purus efficitur ipsum primis in cubilia laoreet augue egestas luctus donec purus and blandit sodales mpedit ligula risus. Mauris donec ociis et magnis sapien',
        "price": 9.99,
        "star": 4,
        "starCount": 89
    }
];

export default fakeData;